version: '3.8'

services:
  zaptap:
    image: tiagotalbuquerque/zaptap:latest
    working_dir: /app
    volumes:
      - zaptap:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - EVOLUTION_API_URL=${EVOLUTION_API_URL}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - API_SECRET_KEY=${API_SECRET_KEY}
    command: >
      sh -c "npm install && npm start"
    restart: unless-stopped

volumes:
  zaptap_data:
    external: true
    name: zaptap_data

networks:
  DQXNetwork: ## Nome da rede interna
    external: true
    name: DQXNetwork ## Nome da rede interna
